Mise à jour du contenu narratif
ansforge/IG-essais-cliniques pull request #17
Opened 2023-07-19 08:37 UTC by sly-kereval

- Correction typo #14 
- Ajout explications mapping
- Correction typo mapping
- Ajout scénario de recherche par identifiant (+ ajout paramètre de recherche)

2023-07-19 08:45 UTC, sdemeyANS requested changes

2023-07-19 08:45 UTC, sdemeyANS commented on input/pagecontent/st_flux1.md
> +GET [BASE]/ResearchStudy?_lastUpdated=ge2022-11-06T15:00 # Critère de recherche sur la date de mise à jour (ge = greater than)
gt = greater than non ? à la place de ge
[the value for the parameter in the resource is greater than the provided value](https://www.hl7.org/fhir/R4/search.html#prefix)

2023-07-19 08:48 UTC, sly-kereval commented on input/pagecontent/st_flux1.md
> +GET [BASE]/ResearchStudy?_lastUpdated=ge2022-11-06T15:00 # Critère de recherche sur la date de mise à jour (ge = greater than)
En effet il y a une erreur, merci ! Par contre d'après la description du scénario on veut supérieur ou égal donc je pense qu'il faut laisser ge mais mettre ge = greater or equal

2023-07-19 11:53 UTC, sdemeyANS commented on input/pagecontent/st_flux1.md
> +GET [BASE]/ResearchStudy?_lastUpdated=ge2022-11-06T15:00 # Critère de recherche sur la date de mise à jour (ge = greater than)
ok à signaler à OCTO du coup car il me semble qu'ils ont mis gt dans leur swagger

2023-07-19 13:22 UTC, NerOcrO commented on input/pagecontent/st_flux1.md
> +GET [BASE]/ResearchStudy?_lastUpdated=ge2022-11-06T15:00 # Critère de recherche sur la date de mise à jour (ge = greater than)
Nous avons géré `gt` et `ge`.

2023-07-21 09:02 UTC, sdemeyANS commented on input/pagecontent/st_flux1.md
> +GET [BASE]/ResearchStudy?_lastUpdated=ge2022-11-06T15:00 # Critère de recherche sur la date de mise à jour (ge = greater than)
@cbihanANS pour info

2023-07-21 09:21 UTC, sdemeyANS approved these changes
je valide. On reviendra si nécessaire sur le point ge / gt

2023-07-21 09:33 UTC, merged