extension contact spécifique au site
ansforge/IG-essais-cliniques pull request #36
Opened 2023-07-27 17:09 UTC by sdemeyANS

ajout ddu profil Location et de l'extension pour le nom du contact spécifique dans location.telecom

2023-07-27 17:20 UTC, nriss requested changes

2023-07-27 17:20 UTC, nriss commented on input/fsh/StructureDefinition/profiles/ECLAIRELocation.fsh
> +* extension contains
L’extension doit être dans Location.telecom

2023-07-28 06:58 UTC, sdemeyANS commented on input/fsh/StructureDefinition/profiles/ECLAIRELocation.fsh
> +* extension contains
Exact je suis allé trop vite

2023-07-28 07:18 UTC, sdemeyANS commented on input/fsh/StructureDefinition/profiles/ECLAIRELocation.fsh
> +* extension contains
@nriss c'est corrigé. merci :)

2023-07-28 07:29 UTC, sly-kereval approved these changes

2023-07-28 07:30 UTC, nriss approved these changes

2023-07-28 07:59 UTC, sly-kereval approved these changes

2023-07-28 08:02 UTC, nriss approved these changes

2023-07-28 08:03 UTC, merged