Ajout flux 2
ansforge/IG-essais-cliniques pull request #63
Opened 2023-09-11 12:12 UTC by sly-kereval

2023-09-12 15:23 UTC, sdemeyANS requested changes
une typo sur flux 1. JE crois qu'il y a aussi une typo sur la page mapping.md sur EclaireLabel dans le texte

2023-09-12 15:23 UTC, sdemeyANS commented on input/pagecontent/st_flux1.md
> +- _content, _text
typo ligne 180-181 Un consommateur souhaite récupér tous

2023-09-13 06:32 UTC, sly-kereval commented on input/pagecontent/st_flux1.md
> +- _content, _text
Merci, c'est corrigé

2023-09-15 13:25 UTC, sdemeyANS approved these changes
ok merci :)
Une relecture complète de la preview de l'IG sera peut-être nécessaire pour faire la chasse aux "typo" :)

2023-09-15 14:00 UTC, merged